first fixes

diff --git a/.github/workflows/build-binary.yaml b/.github/workflows/build-binary.yaml
--- a/.github/workflows/build-binary.yaml
+++ b/.github/workflows/build-binary.yaml
@@ -23,7 +23,7 @@ concurrency:
 jobs:
   setup:
     runs-on: depot-ubuntu-22.04-4
-    name: Setup versions
+    name: Setup
     permissions:
       contents: read
     outputs:
@@ -42,13 +42,77 @@ jobs:
           PREVIOUS_GNOSISVPN_PACKAGE_PR_VERSION: ${{ vars.GNOSISVPN_PACKAGE_PR_VERSION }}
           PREVIOUS_GNOSISVPN_CLI_PR_VERSION: ${{ vars.GNOSISVPN_CLI_PR_VERSION }}
           PREVIOUS_GNOSISVPN_APP_PR_VERSION: ${{ vars.GNOSISVPN_APP_PR_VERSION }}
-        run: "get_latest_pr_version() {\n  local repo=$1\n  local file_path=$2\n  local default_branch\n  default_branch=$(gh api \"repos/gnosis/$repo\" --jq '.default_branch')\n  pr_number=$(gh api \"repos/gnosis/$repo/pulls?state=closed&base=$default_branch&sort=updated&direction=desc&per_page=10\" \\\n    --jq '[.[] | select(.merged_at != null)] | first | .number | tostring')\n  file_content=$(gh api \"repos/gnosis/$repo/contents/$file_path?ref=$default_branch\" --jq '.content' | base64 --decode)\n  if [[ \"$file_path\" == \"package.json\" ]]; then\n    version=$(echo \"$file_content\" | jq -r '.version')\n  else\n    version=$(echo \"$file_content\" | grep '^version\\s*=' | head -n 1 | cut -d '\"' -f 2)\n  fi\n  echo \"$version+pr.$pr_number\"\n}\n\nLATEST_GNOSISVPN_PACKAGE_PR_VERSION=$(get_latest_pr_version \"gnosis_vpn\" \"package.json\")\nLATEST_GNOSISVPN_CLI_PR_VERSION=$(get_latest_pr_version \"gnosis_vpn-client\" \"Cargo.toml\")\nLATEST_GNOSISVPN_APP_PR_VERSION=$(get_latest_pr_version \"gnosis_vpn-app\" \"src-tauri/Cargo.toml\")\nLATEST_GNOSISVPN_PACKAGE_VERSION_NUMBER=$(echo \"$LATEST_GNOSISVPN_PACKAGE_PR_VERSION\" | cut -d '+' -f 1)\nLATEST_GNOSISVPN_PACKAGE_VERSION_PR_NUMBER=$(echo \"$LATEST_GNOSISVPN_PACKAGE_PR_VERSION\" | cut -d '+' -f 2 | cut -d '.' -f 2)\nPREVIOUS_GNOSISVPN_PACKAGE_VERSION_PR_NUMBER=$(echo \"${PREVIOUS_GNOSISVPN_PACKAGE_PR_VERSION}\" | cut -d '+' -f 2 | cut -d '.' -f 2)\necho \"LATEST_GNOSISVPN_PACKAGE_PR_VERSION=$LATEST_GNOSISVPN_PACKAGE_PR_VERSION\" | tee -a \"$GITHUB_OUTPUT\"\n\ncase \"${{ inputs.version_type }}\" in\n  snapshot)\n    echo \"GNOSISVPN_PACKAGE_VERSION=$(date +%Y.%m.%d+build.%H%M%S)\" | tee -a \"$GITHUB_OUTPUT\"\n    echo \"GNOSISVPN_CLI_VERSION=${LATEST_GNOSISVPN_CLI_PR_VERSION}\" | tee -a \"$GITHUB_OUTPUT\"\n    echo \"GNOSISVPN_APP_VERSION=${LATEST_GNOSISVPN_APP_PR_VERSION}\" | tee -a \"$GITHUB_OUTPUT\"\n    ;;\n  commit)\n    sha=\"${{ github.event.pull_request.head.sha }}\"\n    echo \"GNOSISVPN_PACKAGE_VERSION=${LATEST_GNOSISVPN_PACKAGE_VERSION_NUMBER}+commit.${sha:0:7}\" | tee -a \"$GITHUB_OUTPUT\"\n    echo \"GNOSISVPN_CLI_VERSION=${LATEST_GNOSISVPN_CLI_PR_VERSION}\" | tee -a \"$GITHUB_OUTPUT\"\n    echo \"GNOSISVPN_APP_VERSION=${LATEST_GNOSISVPN_APP_PR_VERSION}\" | tee -a \"$GITHUB_OUTPUT\"\n    ;;\n  pr)\n    echo \"GNOSISVPN_PACKAGE_VERSION=${LATEST_GNOSISVPN_PACKAGE_PR_VERSION}\" | tee -a \"$GITHUB_OUTPUT\"\n    echo \"GNOSISVPN_CLI_VERSION=${LATEST_GNOSISVPN_CLI_PR_VERSION}\" | tee -a \"$GITHUB_OUTPUT\"\n    echo \"GNOSISVPN_APP_VERSION=${LATEST_GNOSISVPN_APP_PR_VERSION}\" | tee -a \"$GITHUB_OUTPUT\"\n    ;;\n  release)\n    echo \"GNOSISVPN_PACKAGE_VERSION=${LATEST_GNOSISVPN_PACKAGE_VERSION_NUMBER}\" | tee -a \"$GITHUB_OUTPUT\"\n    echo \"GNOSISVPN_CLI_VERSION=latest\" | tee -a \"$GITHUB_OUTPUT\"\n    echo \"GNOSISVPN_APP_VERSION=latest\" | tee -a \"$GITHUB_OUTPUT\"\n    ;;\n  *)\n    echo \"Invalid version_type: ${{ inputs.version_type }}. Expected snapshot, commit, pr, or release.\"\n    exit 1\n    ;;\nesac\n\nif [[ \"${{ inputs.version_type}}\" == \"snapshot\" ]] && \n   [[ \"${LATEST_GNOSISVPN_PACKAGE_VERSION_PR_NUMBER}\" == \"${PREVIOUS_GNOSISVPN_PACKAGE_VERSION_PR_NUMBER}\" ]] &&\n   [[ \"${LATEST_GNOSISVPN_CLI_PR_VERSION}\" == \"${PREVIOUS_GNOSISVPN_CLI_PR_VERSION}\" ]] &&\n   [[ \"${LATEST_GNOSISVPN_APP_PR_VERSION}\" == \"${PREVIOUS_GNOSISVPN_APP_PR_VERSION}\" ]]; then\n  echo \"SKIP_BUILDING=true\" | tee -a \"$GITHUB_OUTPUT\"\n  echo \"No new merged PRs found for gnosis_vpn, gnosis_vpn-client, or gnosis_vpn-app. Skipping snapshot build.\"\nelse\n  echo \"SKIP_BUILDING=false\" | tee -a \"$GITHUB_OUTPUT\"\n  echo \"Proceeding with the build.\"\nfi\n"
+        run: |
+          apt update && apt install -y jq gh
+          get_latest_pr_version() {
+            local repo=$1
+            local file_path=$2
+            local default_branch
+            default_branch=$(gh api "repos/gnosis/$repo" --jq '.default_branch')
+            pr_number=$(gh api "repos/gnosis/$repo/pulls?state=closed&base=$default_branch&sort=updated&direction=desc&per_page=10" \
+              --jq '[.[] | select(.merged_at != null)] | first | .number | tostring')
+            file_content=$(gh api "repos/gnosis/$repo/contents/$file_path?ref=$default_branch" --jq '.content' | base64 --decode)
+            if [[ "$file_path" == "package.json" ]]; then
+              version=$(echo "$file_content" | jq -r '.version')
+            else
+              version=$(echo "$file_content" | grep '^version\s*=' | head -n 1 | cut -d '"' -f 2)
+            fi
+            echo "$version+pr.$pr_number"
+          }
+
+          LATEST_GNOSISVPN_PACKAGE_PR_VERSION=$(get_latest_pr_version "gnosis_vpn" "package.json")
+          LATEST_GNOSISVPN_CLI_PR_VERSION=$(get_latest_pr_version "gnosis_vpn-client" "Cargo.toml")
+          LATEST_GNOSISVPN_APP_PR_VERSION=$(get_latest_pr_version "gnosis_vpn-app" "src-tauri/Cargo.toml")
+          LATEST_GNOSISVPN_PACKAGE_VERSION_NUMBER=$(echo "$LATEST_GNOSISVPN_PACKAGE_PR_VERSION" | cut -d '+' -f 1)
+          LATEST_GNOSISVPN_PACKAGE_VERSION_PR_NUMBER=$(echo "$LATEST_GNOSISVPN_PACKAGE_PR_VERSION" | cut -d '+' -f 2 | cut -d '.' -f 2)
+          PREVIOUS_GNOSISVPN_PACKAGE_VERSION_PR_NUMBER=$(echo "${PREVIOUS_GNOSISVPN_PACKAGE_PR_VERSION}" | cut -d '+' -f 2 | cut -d '.' -f 2)
+          echo "LATEST_GNOSISVPN_PACKAGE_PR_VERSION=$LATEST_GNOSISVPN_PACKAGE_PR_VERSION" | tee -a "$GITHUB_OUTPUT"
+
+          case "${{ inputs.version_type }}" in
+            snapshot)
+              echo "GNOSISVPN_PACKAGE_VERSION=$(date +%Y.%m.%d+build.%H%M%S)" | tee -a "$GITHUB_OUTPUT"
+              echo "GNOSISVPN_CLI_VERSION=${LATEST_GNOSISVPN_CLI_PR_VERSION}" | tee -a "$GITHUB_OUTPUT"
+              echo "GNOSISVPN_APP_VERSION=${LATEST_GNOSISVPN_APP_PR_VERSION}" | tee -a "$GITHUB_OUTPUT"
+              ;;
+            commit)
+              sha="${{ github.event.pull_request.head.sha }}"
+              echo "GNOSISVPN_PACKAGE_VERSION=${LATEST_GNOSISVPN_PACKAGE_VERSION_NUMBER}+commit.${sha:0:7}" | tee -a "$GITHUB_OUTPUT"
+              echo "GNOSISVPN_CLI_VERSION=${LATEST_GNOSISVPN_CLI_PR_VERSION}" | tee -a "$GITHUB_OUTPUT"
+              echo "GNOSISVPN_APP_VERSION=${LATEST_GNOSISVPN_APP_PR_VERSION}" | tee -a "$GITHUB_OUTPUT"
+              ;;
+            pr)
+              echo "GNOSISVPN_PACKAGE_VERSION=${LATEST_GNOSISVPN_PACKAGE_PR_VERSION}" | tee -a "$GITHUB_OUTPUT"
+              echo "GNOSISVPN_CLI_VERSION=${LATEST_GNOSISVPN_CLI_PR_VERSION}" | tee -a "$GITHUB_OUTPUT"
+              echo "GNOSISVPN_APP_VERSION=${LATEST_GNOSISVPN_APP_PR_VERSION}" | tee -a "$GITHUB_OUTPUT"
+              ;;
+            release)
+              echo "GNOSISVPN_PACKAGE_VERSION=${LATEST_GNOSISVPN_PACKAGE_VERSION_NUMBER}" | tee -a "$GITHUB_OUTPUT"
+              echo "GNOSISVPN_CLI_VERSION=latest" | tee -a "$GITHUB_OUTPUT"
+              echo "GNOSISVPN_APP_VERSION=latest" | tee -a "$GITHUB_OUTPUT"
+              ;;
+            *)
+              echo "Invalid version_type: ${{ inputs.version_type }}. Expected snapshot, commit, pr, or release."
+              exit 1
+              ;;
+          esac
+
+          if [[ "${{ inputs.version_type}}" == "snapshot" ]] &&
+             [[ "${LATEST_GNOSISVPN_PACKAGE_VERSION_PR_NUMBER}" == "${PREVIOUS_GNOSISVPN_PACKAGE_VERSION_PR_NUMBER}" ]] &&
+             [[ "${LATEST_GNOSISVPN_CLI_PR_VERSION}" == "${PREVIOUS_GNOSISVPN_CLI_PR_VERSION}" ]] &&
+             [[ "${LATEST_GNOSISVPN_APP_PR_VERSION}" == "${PREVIOUS_GNOSISVPN_APP_PR_VERSION}" ]]; then
+            echo "SKIP_BUILDING=true" | tee -a "$GITHUB_OUTPUT"
+            echo "No new merged PRs found for gnosis_vpn, gnosis_vpn-client, or gnosis_vpn-app. Skipping snapshot build."
+          else
+            echo "SKIP_BUILDING=false" | tee -a "$GITHUB_OUTPUT"
+            echo "Proceeding with the build."
+          fi
   linux:
     runs-on: ${{ matrix.runner }}
-    name: Build Linux (${{ matrix.nfpm }})
+    name: Build Linux ${{ matrix.nix }}
     if: needs.setup.outputs.SKIP_BUILDING != 'true'
     needs: setup
     strategy:
+      fail-fast: false
       matrix:
         include:
           - nix: x86_64-linux
@@ -84,8 +148,9 @@ jobs:
           GNOSISVPN_PACKAGE_VERSION: ${{ needs.setup.outputs.GNOSISVPN_PACKAGE_VERSION }}
           GNOSISVPN_CLI_VERSION: ${{ needs.setup.outputs.GNOSISVPN_CLI_VERSION }}
           GNOSISVPN_APP_VERSION: ${{ needs.setup.outputs.GNOSISVPN_APP_VERSION }}
-          GNOSISVPN_PREVIOUS_CLI_VERSION: ${{ vars.GNOSISVPN_PREVIOUS_CLI_VERSION }}
-          GNOSISVPN_PREVIOUS_APP_VERSION: ${{ vars.GNOSISVPN_PREVIOUS_APP_VERSION }}
+          GNOSISVPN_PREVIOUS_PACKAGE_VERSION: ${{ vars.GNOSISVPN_PACKAGE_PR_VERSION }}
+          GNOSISVPN_PREVIOUS_CLI_VERSION: ${{ vars.GNOSISVPN_CLI_PR_VERSION }}
+          GNOSISVPN_PREVIOUS_APP_VERSION: ${{ vars.GNOSISVPN_APP_PR_VERSION }}
           GNOSISVPN_GPG_PRIVATE_KEY_PATH: /tmp/gnosis_vpn_gpg_key.asc
           GNOSISVPN_GPG_PRIVATE_KEY_PASSWORD: ${{ secrets.GNOSISVPN_GPG_PRIVATE_KEY_PASSWORD }}
           GNOSISVPN_CHANGELOG_FORMAT: debian
